#!/usr/bin/env bash
# This script runs indefinitely and handles SIGTERM

invincible() {
    echo "I am invincible!!!"
}

trap invincible SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2 &
    wait $!
done
